check/core/urls.py
from django.conf.urls import url, include

from check.core.views import *

urlpatterns = [
    url(r'', include('django.contrib.auth.urls')),

    url(r'^index/', IndexView.as_view(), name='index'),

    url(r'^cliente/$', ListCliente.as_view(), name='list_cliente'),
    url(r'^cliente/add$', CreateCliente.as_view(), name='create_cliente'),
    url(r'^cliente/edit/(?P<pk>\d+)$', UpdateCliente.as_view(), name='update_cliente'),
    url(r'^cliente/delete/(?P<pk>\d+)$', DeleteCliente.as_view(), name='delete_cliente'),

    url(r'^fornecedor/$', ListFornecedor.as_view(), name='list_fornecedor'),
    url(r'^fornecedor/add$', CreateFornecedor.as_view(), name='create_fornecedor'),
    url(r'^fornecedor/edit/(?P<pk>\d+)$', UpdateFornecedor.as_view(), name='update_fornecedor'),
    url(r'^fornecedor/delete/(?P<pk>\d+)$', DeleteFornecedor.as_view(), name='delete_fornecedor'),

    url(r'^banco/$', ListBanco.as_view(), name='list_banco'),
    url(r'^banco/add$', CreateBanco.as_view(), name='create_banco'),
    url(r'^banco/edit/(?P<pk>\d+)$', UpdateBanco.as_view(), name='update_banco'),
    url(r'^banco/delete/(?P<pk>\d+)$', DeleteBanco.as_view(), name='delete_banco'),

    url(r'^empresa/$', UpdateEmpresa.as_view(), name='empresa'),

    url(r'^cheque/emitir/$', ListChequeEmitido.as_view(), name='list_cheque_emissao'),
    url(r'^cheque/emitir/add$', CreateChequeEmitido.as_view(), name='create_cheque_emissao'),
    url(r'^cheque/emitir/edit/(?P<pk>\d+)$', UpdateChequeEmitido.as_view(), name='update_cheque_emissao'),
    url(r'^cheque/emitir/delete/(?P<pk>\d+)$', DeleteChequeEmitido.as_view(), name='delete_cheque_emissao'),

    url(r'^cheque/receber/$', ListChequeRecebido.as_view(), name='list_cheque_recebimento'),
    url(r'^cheque/receber/add$', CreateChequeRecebido.as_view(), name='create_cheque_recebimento'),
    url(r'^cheque/receber/edit/(?P<pk>\d+)$', UpdateChequeRecebido.as_view(), name='update_cheque_recebimento'),
    url(r'^cheque/receber/delete/(?P<pk>\d+)$', DeleteChequeRecebido.as_view(), name='delete_cheque_recebimento'),

    url(r'^baixa/$', BaixaChequesView.as_view(), name='baixa'),
    url(r'^repasse/$', RepasseChequesView.as_view(), name='repasse'),

    url(r'^ajax/get_situacao_cliente/$', get_situacao_cliente, name='get_situacao_cliente'),
    url(r'^ajax/efetuar_baixa/$', efetuar_baixa, name='efetuar_baixa'),
    url(r'^ajax/efetuar_repasse/$', efetuar_repasse, name='efetuar_repasse'),
]

check/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from check import settings
from check.core.views import IndexView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^asu/', admin.site.urls),
    url(r'^core/', include('check.core.urls')),
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

check/core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
from django.utils import timezone


class TemContato(models.Model):
    telefone = models.CharField(max_length=50)
    fax = models.CharField(max_length=50)
    email = models.EmailField()

    class Meta:
        abstract = True

class TemEndereco(models.Model):
    logradouro = models.CharField(max_length=50)
    numero = models.IntegerField()
    bairro = models.CharField(max_length=50)
    cidade = models.CharField(max_length=50)
    uf = models.CharField(max_length=2, verbose_name='UF')
    cep = models.CharField(max_length=50, verbose_name='CEP')

    class Meta:
        abstract = True


class Empresa(TemEndereco, models.Model):
    nome = models.CharField(max_length=50)
    cnpj = models.CharField(max_length=50, verbose_name='CNPJ')
    ie = models.CharField(max_length=50, verbose_name='inscrição estadual')
    # contato
    telefone = models.CharField(max_length=50)
    fax = models.CharField(max_length=50)

    def __str__(self):
        return self.nome


class User(AbstractUser):
    empresa = models.ForeignKey(Empresa, null=True, blank=True)



class Fornecedor(TemContato, TemEndereco, models.Model):
    TIPO_PESSOA = (
        (1, 'PESSOA FÍSICA'),
        (2, 'PESSOA JURÍDICA'),
    )
    nome = models.CharField(max_length=50)
    tipo = models.IntegerField(choices=TIPO_PESSOA, verbose_name='Tipo de pessoa')
    cpf_cnpj = models.CharField(max_length=50, verbose_name='CPF/CNPJ')
    ie = models.CharField(max_length=50, verbose_name='inscrição estadual', blank=True, null=True)
    rg = models.CharField(max_length=50, verbose_name='RG', blank=True, null=True)
    responsavel = models.CharField(max_length=50, verbose_name='responsável')
    data_cadastro = models.DateField(default=timezone.now)


    def __str__(self):
        return self.nome


class Banco(TemContato, TemEndereco, models.Model):
    nome = models.CharField(max_length=50)
    agencia = models.IntegerField(verbose_name='agência')
    contato = models.CharField(max_length=50, verbose_name='pessoa de contato')
    data_cadastro = models.DateField(default=timezone.now)

    def __str__(self):
        return str(self.agencia) + " " + self.nome


class Cliente(TemContato, TemEndereco, models.Model):
    nome = models.CharField(max_length=50)
    cpf = models.CharField(max_length=50, verbose_name='CPF')
    rg = models.CharField(max_length=50, verbose_name='RG')
    data_cadastro = models.DateField(default=timezone.now)

    def __str__(self):
        return self.nome


class Cheque(models.Model):
    TIPO_CHEQUE = (
        (1, "Cheque Pré"),
        (2, "Cheque Pós"),
    )
    numero_cheque = models.IntegerField()
    banco = models.ForeignKey(Banco)
    tipo = models.IntegerField(choices=TIPO_CHEQUE)
    # data_entrada = models.DateField()
    data_desconto = models.DateField()
    valor = models.FloatField()
    data_cadastro = models.DateField(default=timezone.now)

    class Meta:
        abstract = True

class Recebido(Cheque):
    # data_lancamento = models.DateField()
    cliente = models.ForeignKey(Cliente)
    tem_fundo = models.BooleanField(default=True)
    foi_repassado = models.BooleanField(default=False)
    foi_compensado = models.BooleanField(default=False)
    repassado = models.ForeignKey(Fornecedor, blank=True, null=True)

    def __str__(self):
        return str(self.numero_cheque)

class Emitido(Cheque):
    numero_nota = models.IntegerField()
    fornecedor = models.ForeignKey(Fornecedor)
    observacao = models.TextField(blank=True, null=True)

    def __str__(self):
        return str(self.numero_cheque)

check/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from django.db.models import Sum, Count
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView

from check.core.forms import ClienteForm, FornecedorForm, BancoForm, EmpresaForm, ChequeEmitidoForm, ChequeRecebidoForm
from check.core.models import Cliente, Fornecedor, Banco, Empresa, Emitido, Recebido


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        total_emitido = Emitido.objects.all().aggregate(Sum('valor'))
        if total_emitido['valor__sum'] is not None:
            ctx['total_emitido'] = total_emitido
        total_recebido = Recebido.objects.all().aggregate(Sum('valor'))
        if total_recebido['valor__sum'] is not None:
            ctx['total_recebido'] = total_recebido
        total_repassado = Recebido.objects.filter(foi_repassado=True).aggregate(Sum('valor'))
        if total_repassado['valor__sum'] is not None:
            ctx['total_repassado'] = total_repassado
        qtd_com_fundo = Recebido.objects.filter(tem_fundo=True).filter(foi_compensado=True).filter(foi_repassado=False).aggregate(Count('valor'))
        if qtd_com_fundo['valor__count'] is not None:
            ctx['qtd_com_fundo'] = qtd_com_fundo
        qtd_sem_fundo = Recebido.objects.filter(tem_fundo=False).aggregate(Count('valor'))
        if qtd_sem_fundo['valor__count'] is not None:
            ctx['qtd_sem_fundo'] = qtd_sem_fundo
        qtd_nao_descontado = Recebido.objects.filter(foi_compensado=False).filter(foi_repassado=False).aggregate(Count('valor'))
        if qtd_nao_descontado['valor__count'] is not None:
            ctx['qtd_nao_descontado'] = qtd_nao_descontado
        qtd_repassado = Recebido.objects.filter(foi_repassado=True).aggregate(Count('valor'))
        if qtd_repassado['valor__count'] is not None:
            ctx['qtd_repassado'] = qtd_repassado
        ctx['recebidos_desc_hoje'] = Recebido.objects.filter(data_desconto=timezone.now())
        ctx['emitidos_desc_hoje'] = Emitido.objects.filter(data_desconto=timezone.now())
        return ctx


class ListCliente(LoginRequiredMixin, ListView):
    model = Cliente
    template_name = 'object_list.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Cadastros'
        ctx['bread_item'] = 'Cliente'
        ctx['create_url'] = 'create_cliente'
        ctx['edit_url'] = 'update_cliente'
        ctx['delete_url'] = 'delete_cliente'
        return ctx


class CreateCliente(LoginRequiredMixin, CreateView):
    model = Cliente
    form_class = ClienteForm
    template_name = 'object_form.html'
    success_url = reverse_lazy('list_cliente')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Cadastros'
        ctx['bread_item'] = 'Cliente'
        return ctx


class UpdateCliente(LoginRequiredMixin, UpdateView):
    model = Cliente
    form_class = ClienteForm
    template_name = 'object_form.html'
    success_url = reverse_lazy('list_cliente')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Cadastros'
        ctx['bread_item'] = 'Cliente'
        return ctx


class DeleteCliente(LoginRequiredMixin, DeleteView):
    model = Cliente
    template_name = 'object_confirm_delete.html'
    success_url = reverse_lazy('list_cliente')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Cadastros'
        ctx['bread_item'] = 'Cliente'
        return ctx


class ListFornecedor(LoginRequiredMixin, ListView):
    model = Fornecedor
    template_name = 'object_list.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Cadastros'
        ctx['bread_item'] = 'Fornecedor'
        ctx['create_url'] = 'create_fornecedor'
        ctx['edit_url'] = 'update_fornecedor'
        ctx['delete_url'] = 'delete_fornecedor'
        return ctx


class CreateFornecedor(LoginRequiredMixin, CreateView):
    model = Fornecedor
    form_class = FornecedorForm
    template_name = 'object_form.html'
    success_url = reverse_lazy('list_fornecedor')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Cadastros'
        ctx['bread_item'] = 'Fornecedor'
        return ctx


class UpdateFornecedor(LoginRequiredMixin, UpdateView):
    model = Fornecedor
    form_class = FornecedorForm
    template_name = 'object_form.html'
    success_url = reverse_lazy('list_fornecedor')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Cadastros'
        ctx['bread_item'] = 'Fornecedor'
        return ctx


class DeleteFornecedor(LoginRequiredMixin, DeleteView):
    model = Fornecedor
    template_name = 'object_confirm_delete.html'
    success_url = reverse_lazy('list_fornecedor')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Cadastros'
        ctx['bread_item'] = 'Fornecedor'
        return ctx


class ListBanco(LoginRequiredMixin, ListView):
    model = Banco
    template_name = 'object_list.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Cadastros'
        ctx['bread_item'] = 'Banco'
        ctx['create_url'] = 'create_banco'
        ctx['edit_url'] = 'update_banco'
        ctx['delete_url'] = 'delete_banco'
        return ctx


class CreateBanco(LoginRequiredMixin, CreateView):
    model = Banco
    form_class = BancoForm
    template_name = 'object_form.html'
    success_url = reverse_lazy('list_banco')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Cadastros'
        ctx['bread_item'] = 'Banco'
        return ctx


class UpdateBanco(LoginRequiredMixin, UpdateView):
    model = Banco
    form_class = BancoForm
    template_name = 'object_form.html'
    success_url = reverse_lazy('list_banco')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Cadastros'
        ctx['bread_item'] = 'Banco'
        return ctx


class DeleteBanco(LoginRequiredMixin, DeleteView):
    model = Banco
    template_name = 'object_confirm_delete.html'
    success_url = reverse_lazy('list_banco')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Cadastros'
        ctx['bread_item'] = 'Banco'
        return ctx


class UpdateEmpresa(LoginRequiredMixin, UpdateView):
    model = Empresa
    form_class = EmpresaForm
    template_name = 'object_form.html'
    success_url = reverse_lazy('index')

    def get_object(self):
        print(self.request.user.empresa)
        print(type(self.request.user.empresa))
        try:
            return Empresa.objects.get(id=self.request.user.empresa.id)
        except Exception:
            return None;

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Cadastros'
        ctx['bread_item'] = 'Empresa'
        if self.get_object() == None:
            ctx['alert_danger'] = 'Você ainda não fez a configuração inicial da sua empresa'
        return ctx


class ListChequeEmitido(LoginRequiredMixin, ListView):
    model = Emitido
    template_name = 'cheque_list.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Controle de cheques'
        ctx['bread_item'] = 'Emissão'
        ctx['create_url'] = 'create_cheque_emissao'
        ctx['edit_url'] = 'update_cheque_emissao'
        ctx['delete_url'] = 'delete_cheque_emissao'
        return ctx


class CreateChequeEmitido(LoginRequiredMixin, CreateView):
    model = Emitido
    form_class = ChequeEmitidoForm
    template_name = 'object_form.html'
    success_url = reverse_lazy('list_cheque_emissao')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Controle de cheques'
        ctx['bread_item'] = 'Emissão'
        return ctx


class UpdateChequeEmitido(LoginRequiredMixin, UpdateView):
    model = Emitido
    form_class = ChequeEmitidoForm
    template_name = 'object_form.html'
    success_url = reverse_lazy('list_cheque_emissao')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Controle de cheques'
        ctx['bread_item'] = 'Emissão'
        return ctx


class DeleteChequeEmitido(LoginRequiredMixin, DeleteView):
    model = Emitido
    template_name = 'object_confirm_delete.html'
    success_url = reverse_lazy('list_cheque_emissao')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Controle de cheques'
        ctx['bread_item'] = 'Recebimento'
        return ctx


class ListChequeRecebido(LoginRequiredMixin, ListView):
    model = Recebido
    template_name = 'cheque_list.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['bread_menu'] = 'Controle de cheques'
        ctx['bread_item'] = 'Recebimento'
        ctx['create_url'] = 'create_cheque_recebimento'
        ctx['edit_url'] = 'update_cheque_recebimento'
        ctx['delete_url'] = 'delete_cheque_recebimento'
        return ctx


class CreateChequeRecebido(LoginRequiredMixin, CreateView):

check/templates/baixa.html
{% extends 'template.html' %}


{% block content %}
<div class="card">
    <div class="card-body">

<h4>Baixa de cheques</h4>



<form class="container">

  <div class="row">

    <div class="col-md-3 mb-3">
      <label for="select">Coluna</label>
       <select id="select" class="form-control">
        <option value="0" selected>Número</option>
        <option value="1">Data de emissão</option>
        <option value="2">Emitente</option>
        <option value="3">Agência</option>
        <option value="4">Banco</option>
    </select>
    </div>
    <div class="col-md-3 mb-3">
      <label for="input">Pesquisa</label>
       <input type="text" class="form-control" id="input" placeholder="pesquisar"
           onkeyup="pesquisar()"/>

    </div>

  </div>
</form>

<table class="table table-hover col-lg-12" id="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Data de emissão</th>
        <th scope="col">Emitente</th>
        <th scope="col">Agência</th>
        <th scope="col">Banco</th>
        <th scope="col">Sem fundo</th>
        <th scope="col">Foi compensado</th>
        <th scope="col">Valor</th>
        <th scope="col">Baixar</th>

    </tr>
    </thead>
    <tbody>
    {% for cheque in object_list %}

    <tr class="{% if not cheque.tem_fundo%}table-danger{% elif cheque.foi_compensado %}text-success{% endif %}">
        <td>{{ cheque.numero_cheque }}</td>
        <td>{{ cheque.data_cadastro | date:"d/m/Y" }}</td>
        <td>{{ cheque.cliente }}</td>
        <td>{{ cheque.banco.agencia }}</td>
        <td>{{ cheque.banco.nome }}</td>
        <td>{{ cheque.tem_fundo | yesno:"sim,não"}}</td>
        <td>{{ cheque.foi_compensado | yesno:"sim,não" }}</td>
        <td>{{ cheque.valor }}</td>
        <td><a href="javascript:void(0)" onclick="efetuar_baixa({{ cheque.id }})"><i class="fa fa-check"></i></a></td>
    </tr>

    {% endfor %}
    </tbody>
</table>
    </div>
</div>


{% endblock %}

{% block js %}
<script>
function pesquisar() {
   var index = $("#select").val();
  // Declare variables
  var input, filter, table, tr, td, i;
  input = document.getElementById("input");
  filter = input.value.toUpperCase();
  table = document.getElementById("table");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[index];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}


</script>
<script>
function efetuar_baixa(id) {
    swal({
        title: 'Atenção',
        text: "O cheque tem fundo?",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Sim',
        cancelButtonText: 'Não'
    }).then((result) => {
            $.ajax({
                url: '{% url "efetuar_baixa" %}',
                data: {
                    'id': id,
                    'tem_fundo': result.value
                },
                dataType: 'json',
                success: function(data) {
                    console.log(data)

                }
            });
            if (result.value) {


               swal({
                    title: 'Realizando baixa',
                    text: 'O cheque foi marcado com fundo',
                    type: 'success',
                    timer: 2000,
                    onOpen: () => {
                        swal.showLoading()
                    }
                }).then((result) => {
                    if (result.dismiss === 'timer') {
                        location.reload();
                    } else {
                        location.reload();
                    }
                });
            } else {
                swal({
                    title: 'Realizando baixa',
                    text: 'O cheque foi marcado sem fundo',
                    type: 'error',
                    timer: 2000,
                    onOpen: () => {
                        swal.showLoading()
                    }
                }).then((result) => {
                    if (result.dismiss === 'timer') {
                        location.reload();
                    } else {
                        location.reload();
                    }
                });
            }
        });

    }



</script>
{% endblock %}

check/templates/cheque_list.html
{% extends 'template.html' %}

{% block content %}

<div class="card">
    <div class="card-body">
        <h4>{{ bread_item }} de cheques</h4>
        <a class="btn btn-primary" style="margin: 10px 0px 20px;" href="{% url create_url %}">Incluir {{ bread_item | lower }}</a>
        <ul class="list-group">
            {% if object_list %}
            {% for object in object_list %}
            <li class="list-group-item list-group-item-action"
                style="display: flex; justify-content: space-between;">

                {{ object }}
                <div>
                    <a href="{% url edit_url object.id %}" style="margin-right: 15px;"> <i class="fa fa-pencil"></i></a>
                    <a href="{% url delete_url object.id %}">  <i class="fa fa-trash"></i></a>
                </div>
            </li>
            {% endfor %}
            {% else %}
            <li class="list-group-item list-group-item-action">
                Não há registros ainda
            </li>
            {% endif %}
        </ul>
    </div>
</div>
{% endblock %}

check/templates/cheque_recebimento_form.html
{% extends 'template.html' %}

{% load crispy_forms_tags  %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h4>Cadastro de {{ bread_item | lower}}</h4>
        {% crispy form  %}
    </div>
</div>
{% endblock %}

{% block js %}
<script>

$("#id_cliente").change(function() {
    $.ajax({
        url: '{% url "get_situacao_cliente" %}',
        data: {
            'id': $(this).val(),
        },
        dataType: 'json',
        success: function (data) {
        console.log(data)
            if (data['quantidade'] > 0){
                 $("#id_cliente").addClass("is-invalid");
                 if ($("#cliente_situacao_invalida").html() == undefined){

                 $("#div_id_cliente > div.col-lg-12").append('<span id="cliente_situacao_invalida" class="invalid-feedback"><strong>O cliente possui cheques sem fundo.</strong></span>');
                 }
                 var cheque = ' cheques ';
                if(data['quantidade'] == 1){
                    cheque = ' cheque ';
                }
            var mensagem = 'Este cliente possui ' + data['quantidade'] + cheque + 'sem fundo'
                swal('Atenção', mensagem,'error');

             } else {
                    $("#id_cliente").removeClass("is-invalid");
                    $("#cliente_situacao_invalida").detach();
             }
        }
    });
});



</script>
{% endblock %}

check/templates/object_confirm_delete.html
{% extends 'template.html' %}

{% block content %}
<div class="card">
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <h4>Confirmar exclusão</h4>
            <p>Você confirma a exclusão de {{ bread_item | lower }} <strong> {{ object }}</strong>?</p>
            <p>
                <small>Esta operação não pode ser desfeita!</small>
            </p>
            <hr/>
            <input class="btn btn-danger" type="submit" value="Excluir"/>
        </form>
    </div>
</div>
{% endblock %}

check/templates/object_form.html
{% extends 'template.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h4>Cadastro de {{ bread_item | lower}}</h4>
        {% crispy form %}
    </div>
</div>
{% endblock %}

check/templates/object_list.html
{% extends 'template.html' %}

{% block content %}



<div class="card">
    <div class="card-body">
        <h4>Listagem de {{ bread_item | lower }}</h4>
        <a class="btn btn-primary" style="margin: 10px 0px 20px;" href="{% url create_url %}">Adicionar</a>
        <ul class="list-group">
            {% if object_list %}
            {% for object in object_list %}
            <li class="list-group-item list-group-item-action"
                style="display: flex; justify-content: space-between;">

                {{ object }}
                <div>
                    <a href="{% url edit_url object.id %}" style="margin-right: 15px;"> <i class="fa fa-pencil"></i></a>
                    <a href="{% url delete_url object.id %}">  <i class="fa fa-trash"></i></a>
                </div>
            </li>
            {% endfor %}
            {% else %}
            <li class="list-group-item list-group-item-action">
                Não há registros ainda
            </li>
            {% endif %}
        </ul>
    </div>
</div>
{% endblock %}